services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: task
      POSTGRES_PASSWORD: task
    ports:
      - "5440:5432"
    volumes:
      - ./target/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task -d taskdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    # Option A (Dockerfile build): uncomment build and comment image
    build: .
    # Option B (Jib): comment build and use image after mvn jib:dockerBuild
    #image: ghcr.io/sgaraba/task-api:dev
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
      SPRING_DATASOURCE_USERNAME: task
      SPRING_DATASOURCE_PASSWORD: task
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_LIQUIBASE_ENABLED: "true"
    ports:
      - "8080:8080"
